spring:
  datasource:
      url: jdbc:log4jdbc:mariadb://localhost:3306/monkey?useSSL=false&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: root
      password: qwer1234
batch:
  initialize-schema: never